# SITE CONFIGURATION
#baseurl: "/Type-on-Strap"
#url: "https://sylhare.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Devon Drum Lessons
  description: Drumming lessons in Devon from a friendly tutor based in Cullompton near Exeter and Tiverton
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
        <h1 class="title">Devon Drum Lessons</h1> 
        <h2 class="subtitle">Friendly tutor based in Cullompton</h2>
        <p>Within easy reach of Exeter and Tiverton</p>
  header_text_feature_image: assets/img/pexels/feature-img-home.jpg
  footer_text: "&copy; 2018 Devon Drum Lessons"
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  tel: 07777 777777
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: 
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: false
  search: false
  tags: false
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-remote-theme, jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # If using the theme as a jekyll theme gem
remote_theme: Sylhare/Type-on-Strap
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]